<?php

return [
    [
        "arabic"=> "اللّهُ لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ (آية الكرسي)",
        "ajami"=> "Allâhu lâ ilâha illâ huwa-l-hayyu-l-qayyûm. Lâ ta'khudhuhu sinatun wa lâ nawm, lahu mâ fî s-samâwâti wa mâ fî-l-ard. Man dhâ l-ladhî yashfacu cindahu illâ bi-idhnihi. Yaclamu mâ bayna aydîhim wa mâ khalfahum. Wa lâ yuhîtûna bi-shay'in min cilmihi illâ bi-mâ shâ'a. Wasica kursiyyuhu s-samâwâti wa-l-ard. Wa lâ ya'ûduhu hifzuhumâ, wa huwa-l-caliyyu-l-cazîm.",
        "hausa"=> "Allah ne, babu abin bauta sai Shi, Mai Rayuwa, Mai Tsaye da Kansa. Barci mai nauyi ko mai sauƙi ba ya ɗauke Shi. Abin da ke cikin sammai da abin da ke cikin ƙasa na Shi ne. Wane ne zai yi ceto a wurinSa face da izininSa? Ya san abin da ke gabaninsu da abin da ke bayansu, kuma ba za su iya kewaye wani abu ba daga iliminSa sai abin da Ya so. KursiyyunSa ya yalwaci sammai da ƙasa, kuma kiyaye su ba ya nauyaya Masa. Kuma Shi ne Maɗaukaki, Mai Girma.",
        "count"=> 1,
    ],
    [
        "arabic"=> "قُـلْ هُـوَ اللهُ أَحَـدٌ …..( [ الإِخْـلاصْ ] ) قُـلْ أَعـوذُ بِرَبِّ الفَلَـقِ…..( [ الفَلَـقْ ] ) قُـلْ أَعـوذُ بِرَبِّ النّـاسِ…..([ الـنّاس])",
        "ajami"=> "Qul huwa l-lâhu ahad, Allâhu s-samad, Lam yalid wa lam yûlad, Wa lam yakun lahû kufuwan ahad. (Al-Ikhlas) Qul acûdhu bi-rabbi-l falaq, min sharri mâ khalaq, wa min sharri ghâsiqin idha waqab, wa min sharri n-naffâthâti fi-l cuqad. wa min sharri hâsidin idhâ hasad. (Al-Falaq) Qul acûdhu bi-rabbi n-nâs, maliki n-nâs, ilâhi n-nâs. Min sharri-l-waswâsi-l-khannâs, al-ladhî yuwaswisu fî sudûri n-nâs, min al jinnati wa n-nâs. (An-Nas)",
        "hausa"=> "Ka ce=> Shi ne Allah Makaɗaici. Allah Shi ne Abin Nufi. Bai haifa ba, kuma ba a haife Shi ba. Kuma babu wanda ya zama daidai da Shi. Ka ce=> Ina neman tsari da Ubangijin asuba, daga sharrin abin da Ya halitta. Kuma daga sharrin mai duhu idan ya yi, kuma daga sharrin masu hura a cikin kuɗi, kuma daga sharrin mai hassada idan ya yi hassada. Ka ce=> Ina neman tsari da Ubangijin mutane, Sarkin mutane, Abin bautawar mutane. Daga sharrin mai zugawa, mai janyewa. Wanda ke zugawa a cikin ƙirazan mutane, daga aljannu da mutane.",
        "count"=> 3,
    ],
    [
        "arabic"=> "أَصْبَحْـنا وَأَصْبَـحَ المـلكُ لله وَالحَمدُ لله ، لا إلهَ إلاّ اللّهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمْـد، وهُوَ على كلّ شَيءٍ قدير ، رَبِّ أسْـأَلُـكَ خَـيرَ ما في هـذا الـيَوْمِ وَخَـيرَ ما بَعْـدَه ، وَأَعـوذُ بِكَ مِنْ شَـرِّ ما في هـذا الـيَوْمِ وَشَرِّ ما بَعْـدَه ، رَبِّ أَعـوذُبِكَ مِنَ الْكَسَـلِ وَسـوءِ الْكِـبَر ، رَبِّ أَعـوذُبِكَ مِنْ عَـذابٍ في النّـارِ وَعَـذابٍ في القَـبْر",
        "ajami"=> "Asbahnâ wa asbaha-l-mulku li-l-lâhi, wa-l-hamdu li-l-lâhi. Lâ ilâha illâ l-lâhu, wahdahu lâ sharîka lahu, lahu-l-mulku wa lahu-l-hamdu, wa huwa calâ kulli shay'in qadîr. Rabbi, as'aluka khayra mâ fî hâdhâ-l-yawmi wa khayra mâ bacdahu. Wa acûdhu bika min sharri mâ fî hâdhâ-l-yawmi wa sharri mâ bacdahu. Rabbi acûdhu bika mina-l-kasali, wa sû'i-l-kibari. Rabbi acûdhu bika min cadhâbin fi n-nâr wa cadhâbin fi-l-qabr.",
        "hausa"=> "Mun shiga safiya kuma a wannan lokaci dukkan mulki na Allah ne, kuma godiya ta tabbata ga Allah. Babu abin bauta da cancanta sai Allah, Shi kaɗai, ba Shi da abokin tarayya, Mulki na Shi ne, kuma godiya ta tabbata a gare Shi, kuma Shi Mai Iko ne a kan kowane abu. Ya Ubangijina, Ina roƙonka alherin wannan rana da alherin abin da ke bayanta, kuma ina neman tsari da Kai daga sharrin wannan rana da sharrin abin da ke bayanta. Ya Ubangijina, Ina neman tsari da Kai daga kasala da mugun tsufa. Ya Ubangijina, Ina neman tsari da Kai daga azabar wuta da azabar kabari.",
        "count"=> 1,
    ],
    [
        "arabic"=> "اللّهُـمَّ بِكَ أَصْـبَحْنا وَبِكَ أَمْسَـينا ، وَبِكَ نَحْـيا وَبِكَ نَمـوتُ وَإِلَـيْكَ النِّـشور",
        "ajami"=> "Allahumma bika asbahnâ, wa bika amsaynâ, wa bika nahyâ, wa bika namûtu, wa ilayka n-nushûr.",
        "hausa"=> "Ya Allah, da IzininKa muka shiga safiya, kuma da IzininKa muke shiga maraice, da IzininKa muke rayuwa, kuma da IzininKa muke mutuwa, kuma zuwa gare Ka ne tashinmu (ranar alƙiyama).",
        "count"=> 1,
    ],
    [
        "arabic"=> "اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ ، خَلَقْتَنـي وَأَنا عَبْـدُك ، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت ، أَعـوذُبِكَ مِنْ شَـرِّ ما صَنَـعْت ، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ",
        "ajami"=> "Allâhumma anta rabbî, lâ ilâha illâ anta. Khalaqtanî wa anâ cabduka, wa anâ calâ cahdika wa wacdika mâ stata'tu. Acûdhu bika min sharri mâ sana'tu. Abû'u laka bi-nicmatika calayya wa abû'u bi-dhanbî. Fa-ghfir lî fa-innahu lâ yaghfiru dh-dhunûba illâ ant.",
        "hausa"=> "Ya Allah, Kai ne Ubangijina, babu abin bauta sai Kai, Ka halicce ni kuma ni bawonKa ne, kuma ina kan alƙawarinKa da wa'adinKa gwargwadon iyawa ta. Ina neman tsari da Kai daga sharrin abin da na aikata. Na tabbatar da ni'imarKa a kaina, kuma na tabbatar da zunubina, saboda haka Ka gafarta mini, domin lalle babu mai gafarta zunubai sai Kai.",
        "count"=> 1,
    ],
    [
        "arabic"=> "اللّهُـمَّ إِنِّـي أَصْبَـحْتُ أَُشْـهِدُك ، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك ، وَمَلائِكَتِك ، وَجَمـيعَ خَلْـقِك ، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـك ، وَأَنَّ ُ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك",
        "ajami"=> "Allâhumma innî asbahtu ush-hiduka, wa ush-hidu hamalata carshika, wa malâ'ikataka, wa jamîca khalqika, annaka anta l-lâhu, lâ ilâha illâ anta, wahdaka lâ sharîka laka, wa anna Muhammadan [sallallahu calayhi wa sallama] cabduka wa rasûluk.",
        "hausa"=> "Ya Allah, lalle ni na shiga safiya ina shaida Kai, kuma ina shaida masu ɗaukar Al'arshinKa, da Mala'ikunKa, da kuma dukkan halittunKa, cewa lalle Kai ne Allah, babu abin bauta da cancanta sai Kai, Kai kaɗai, ba Ka da abokin tarayya, kuma lalle Muhammadu bawanKa ne kuma ManzonKa ne.",
        "count"=> 4,
    ],
    [
        "arabic"=> "اللّهُـمَّ ما أَصْبَـَحَ بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك ، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك ، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر",
        "ajami"=> "Allâhumma mâ asbaha bî min nicmatin aw bi-ahadin min khalqika, fa-minka wahdaka lâ sharîka laka. Fa-laka-l-hamdu wa laka sh-shukr.",
        "hausa"=> "Ya Allah, duk wata ni'ima da ni ko wani daga cikin halittarKa suka wayi gari da ita, to daga gare Ka kaɗai take, ba Ka da abokin tarayya, saboda haka godiya ta tabbata a gare Ka kuma yabo na tabbata a gare Ka.",
        "count"=> 1,
    ],
    [
        "arabic"=> "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصْرِي، لاَ إِلَهَ إِلاَّ أَنْتَ... اللَّهُمَّ إِنِّي أَعُوْذُ بِكَ مِنَ الْكُفْرِ، وَالْفَقْرِ، وأَعُوْذُ بِكَ مِنْ عَذَابِ القَبْرِ، لاَ إِلَهَ إِلاَّ أَنْتَ",
        "ajami"=> "Allâhumma câfinî fî badanî. Allâhumma câfinî fî samcî. Allâhumma câfinî fî basarî. Lâ ilâha illâ anta. Allâhumma innî acûdhu bika mina-l-kufri, wa-l-faqri. Wa acûdhu bika min cadhâbi-l-qabri. Lâ ilâha illâ anta.",
        "hausa"=> "Ya Allah, Ka ba jikina lafiya. Ya Allah, Ka ba jinina lafiya. Ya Allah, Ka ba ganina lafiya. Babu abin bauta sai Kai. Ya Allah, Ina neman tsari da Kai daga kafirci da talauci, kuma ina neman tsari da Kai daga azabar kabari. Babu abin bauta sai Kai.",
        "count"=> 3,
    ],
    [
        "arabic"=> "حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم",
        "ajami"=> "Hasbiya l-lâhu lâ ilâha illâ huwa calayhi tawakkaltu, wa huwa rabbu-l-carshi-l-cazîmi.",
        "hausa"=> "Allah Ya isar mini, babu abin bauta sai Shi, a gare Shi na dogara, kuma Shi ne Ubangijin Al'arshi Mai Girma.",
        "count"=> 7,
    ],
    [
        "arabic"=> "اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي ، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي ، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي ، وَمِن فَوْقـي ، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي",
        "ajami"=> "Allâhummâ innî as'aluka-l-cafwa wa-l-câfiyata fi d-duniyâ wa-l-âkhirati. Allâhummâ innî as'aluka-l-cafwa wa-l-câfiyata fî dînî, wa dunyâya, wa ahlî, wa mâlî. Allâhumma stur cawrâtî, wa âmin rawcâtî. Allahumma hfaznî minm bayna yadayya, wa min khalfî, wa can yamînî, wa can shimâlî, wa min fawqî. Wa acûdhu bi azamatika an ughtâla min tahtî.",
        "hausa"=> "Ya Allah, Ina roƙonKa gafara da aminci a wannan duniya da Lahira. Ya Allah, Ina roƙonKa gafara da aminci a cikin addinina da duniyata, da iyalina da dukiyata. Ya Allah, Ka rufe al’aurata, kuma Ka kwantar da tsorona. Ya Allah, Ka kiyaye ni daga gabana da daga bayana, da daga damana da daga haguna, kuma daga samana, kuma ina neman tsari da girmanKa kada a halaka ni daga ƙasata.",
        "count"=> 1,
    ],
    [
        "arabic"=> "اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه ، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت ، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِـرْكِه ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم",
        "ajami"=> "Allâhumma câlim-alghaybi wa sh-shahâdati, fâtira s-samâwâti wa-l ardi, rabba kulli shay'in wa malîkahu. Ash-hadu anlâ ilâha illâ anta. Acûdhu bika min sharrin nafsî, wa min sharri sh-shaytâni wa chirkihi, wa an aqtarifa calâ nafsî sû'an ajurrahu ilâ mouslim(in).",
        "hausa"=> "Ya Allah, Masanin gaibi da bayyane, Mahaliccin sammai da ƙasa, Ubangiji kuma Mai mulkin kowane abu, Ina shaida cewa babu abin bauta sai Kai. Ina neman tsari da Kai daga sharrin raina, da daga sharrin Shaiɗan da shirkinsa, kuma daga in aikata mugunta a kan raina, ko in jawo ta ga wani Musulmi.",
        "count"=> 1,
    ],
    [
        "arabic"=> "بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم",
        "ajami"=> "Bismi l-lâhi l-ladhî lâ yadurrû maca smihi shay'un fi-l ardi wa lâ fi s-samâ'i, wa huwa s-samic-ul-calîm.",
        "hausa"=> "Da sunan Allah, wanda babu abin da ke cutarwa tare da sunanSa a ƙasa ko a sama, kuma Shi ne Mai ji, Masani.",
        "count"=> 3,
    ],
    [
        "arabic"=> "رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ نَبِيّـاً",
        "ajami"=> "Radîtu bi-l-lâhi rabban, wa bi-l-islâmi dînan, wa bi muhammadin [sallallahu calayhi wa sallama] nabiyyan.",
        "hausa"=> "Na yarda da Allah a matsayin Ubangiji, kuma da Musulunci a matsayin addini, kuma da Muhammadu a matsayin Annabi.",
        "count"=> 3,
    ],
    [
        "arabic"=> "يا حَـيُّ يا قَيّـومُ بِـرَحْمَـتِكِ أَسْتَـغـيث ، أَصْلِـحْ لي شَـأْنـي كُلَّـه ، وَلا تَكِلـني إِلى نَفْـسي طَـرْفَةَ عَـين",
        "ajami"=> "Yâ hayyû, yâ qayyûmu bi rahmatika astaghîth(u). Aslih lî sha'nî kullah(u) wa lâ takilnî ilâ nafsî tarfata cayn(in).",
        "hausa"=> "Ya Rayayye, Ya Mai Tsaye da Kansa, da rahamarKa nake neman taimako, Ka gyara mini dukkan al'amurana, kuma kada Ka bar ni ga kaina, koda na kiftawar ido ne.",
        "count"=> 1,
    ],
    [
        "arabic"=> "أَصْبَـحْـنا وَأَصْبَـحْ المُـلكُ للهِ رَبِّ العـالَمـين ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ خَـيْرَ هـذا الـيَوْم ، فَـتْحَهُ ، وَنَصْـرَهُ ، وَنـورَهُ وَبَـرَكَتَـهُ ، وَهُـداهُ ، وَأَعـوذُ بِـكَ مِـنْ شَـرِّ ما فـيهِ وَشَـرِّ ما بَعْـدَه",
        "ajami"=> "Asbahnâ wa asbaha-l-mulku li-l-lâhi rabbi-l-câlamîn. Allahumma innî as'aluka khayra hâdhâ-l-yawmi=> fathahu, wa nusrahu, wa nûrahu, wa barakatahu, wa hudâhu. Wa acûdhu bika min sharri mâ fîhi wa sharri mâ bacdahu.",
        "hausa"=> "Mun shiga safiya kuma a wannan lokaci dukkan mulki na Allah ne, Ubangijin talikai. Ya Allah, Ina roƙonKa alherin wannan rana=> nasararta, da taimakon ta, da haskenta, da albarkarta, da shiryarta. Kuma ina neman tsari da Kai daga sharrin abin da ke cikinta da sharrin abin da ke bayanta.",
        "count"=> 1,
    ],
    [
        "arabic"=> "أَصْـبَحْنا علـى فِطْـرَةِ الإسْلام ، وَعَلـى كَلِـمَةِ الإخْـلاص ، وَعلـى دينِ نَبِـيِّنا مُحَـمَّدٍ وَعَاـى مِلَّـةِ أبينـا إِبْـراهيـمَ حَنيـفاً مُسْلِـماً وَمـا كـانَ مِنَ المُشـرِكيـن",
        "ajami"=> "Asbahna calâ fitrati-l-islâmi, wa calâ kalimati-l-ikhlâsi, wa calâ nabiyyinâ Muhammadin, wa calâ millati abîna Ibrâhîma, hanîfan, musliman, wa mâ kâna mina-l-mushrikîn.",
        "hausa"=> "Mun wayi gari a kan fitirar Musulunci, kuma a kan kalmar Ikhlasi (tsarkakakken imani), kuma a kan addinin Annabinmu Muhammadu (S.A.W), kuma a kan addinin ubanmu Ibrahim, wanda ya kasance mai karkata (zuwa ga gaskiya), musulmi, kuma bai kasance daga cikin masu shirka ba.",
        "count"=> 1,
    ],
    [
        "arabic"=> "سُبْحـانَ اللهِ وَبِحَمْـدِهِ",
        "ajami"=> "Subhâna l-lâhi wa bi-hamdihi.",
        "hausa"=> "Tsarki ya tabbata ga Allah kuma ina yabonSa.",
        "count"=> 100,
    ],
    [
        "arabic"=> "لا إلهَ إلاّ اللّهُ وحْـدَهُ لا شَـريكَ لهُ، لهُ المُـلْكُ ولهُ الحَمْـد، وهُوَ على كُلّ شَيءٍ قَدير",
        "ajami"=> "Lâ ilâha illa l-lâhu wahdahu lâ sharîka lah(u) lahu-l-mulku walahu-l-hamd(u), wa huwa calâ kulli shay'in qadîr.",
        "hausa"=> "Babu abin bauta sai Allah, Shi kaɗai, ba Shi da abokin tarayya, Mulki na Shi ne, kuma godiya ta tabbata a gare Shi, kuma Shi Mai Iko ne a kan kowane abu.",
        "count"=> 10,
    ],
    [
        "arabic"=> "لا إلهَ إلاّ اللّهُ وحْـدَهُ لا شَـريكَ لهُ، لهُ المُـلْكُ ولهُ الحَمْـد، وهُوَ على كُلّ شَيءٍ قَدير",
        "ajami"=> "Lâ ilâha illa l-lâhu wahdahu lâ sharîka lah(u) lahu-l-mulku walahu-l-hamd(u), wa huwa calâ kulli shay'in qadîr.",
        "hausa"=> "Babu abin bauta sai Allah, Shi kaɗai, ba Shi da abokin tarayya, Mulki na Shi ne, kuma godiya ta tabbata a gare Shi, kuma Shi Mai Iko ne a kan kowane abu.",
        "count"=> 100,
    ],
    [
        "arabic"=> "سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِه ، وَرِضـا نَفْسِـه ، وَزِنَـةَ عَـرْشِـه ، وَمِـدادَ كَلِمـاتِـه",
        "ajami"=> "Subhâna l-lâhi wa bi-hamdihi, cadada khaqihi, wa ridâ nafsihi, wa zinata carshihi, wa midâda kalimâtihi.",
        "hausa"=> "Tsarki ya tabbata ga Allah kuma ina yabonSa, adadin halittunSa, da yardar KanSa, da nauyin Al'arshinSa, da tawadar kalmominSa.",
        "count"=> 3,
    ],
    [
        "arabic"=> "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْماً نَافِعاً، وَ رِزْقاً طَيِّباً، وَ عَمَلاً مُتَقَبَّلاً",
        "ajami"=> "Allahumma innî as'aluka cilman nâfican, wa rizqan tayyiban, wa camalan mutaqabbalan.",
        "hausa"=> "Ya Allah, Ina roƙonKa ilimi mai amfani, da arziki mai kyau, da aiki karɓaɓɓe.",
        "count"=> 1,
    ],
    [
        "arabic"=> "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
        "ajami"=> "Astaghfiru l-lâha wa atûbu ilayh(i).",
        "hausa"=> "Ina neman gafarar Allah kuma na tuba zuwa gare Shi.",
        "count"=> 100,
    ],
    [
        "arabic"=> "اللَّهُمَّ صَلِّ وَ سَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ",
        "ajami"=> "Allahumma salli wa sallim calâ nabiyyinâ Muhammad.",
        "hausa"=> "Ya Allah, Ka yi salati da sallama a kan Annabinmu Muhammadu.",
        "count"=> 10,
    ],
];
